openapi: '3.0.3'
info:
  description: |
    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more.
  version: '1.0.0'
  title: 'Spotify Web API'
  termsOfService: 'https://developer.spotify.com/terms/'
  servers:
    - url: https://api.spotify.com/v1
paths:
  /albums/{id}:
    get:
      operationId: get-an-album
      tags:
        - Albums
      summary: Get Album
      description: Get Spotify catalog information for a single album.
      security:
        - oauth_2_0: []
  /albums/{id}/tracks:
    get:
      operationId: get-an-albums-tracks
      tags:
        - Albums
        - Tracks
      summary: Get Album Tracks
      description: Get Spotify catalog information about an album’s tracks. Optional parameters can be used to limit the number of tracks returned.
      security:
        - oauth_2_0: []
  /artists/{id}:
    get:
      tags:
        - Artists
      operationId: get-an-artist
      summary: Get Artist
      description: Get Spotify catalog information for a single artist identified by their unique Spotify ID.
      security:
        - oauth_2_0: []

  /artists/{id}/albums:
    get:
      tags:
        - Artists
        - Albums
      operationId: get-an-artists-albums
      summary: Get Artist's Albums
      description: Get Spotify catalog information about an artist's albums.
      security:
        - oauth_2_0: []
  /artists/{id}/top-tracks:
    get:
      tags:
        - Artists
        - Tracks
      operationId: get-an-artists-top-tracks
      summary: Get Artist's Top Tracks
      description: Get Spotify catalog information about an artist's top tracks by country.
      security:
        - oauth_2_0: []

  /tracks/{id}:
    get:
      tags:
        - Tracks
      operationId: get-track
      summary: Get Track
      description: Get Spotify catalog information for a single track identified by its unique Spotify ID.
      security:
        - oauth_2_0: []
  /tracks:
    get:
      tags:
        - Tracks
      operationId: get-several-tracks
      summary: |
        Get Several Tracks
      description: |
        Get Spotify catalog information for multiple tracks based on their Spotify IDs.
      security:
        - oauth_2_0: []

  /me/playlists:
    get:
      tags:
        - Playlists
        - Library
      operationId: get-a-list-of-current-users-playlists
      summary: Get Current User's Playlists
      description: Get a list of the playlists owned or followed by the current Spotify user.
      security:
        - oauth_2_0:
            - playlist-read-private
  /me/albums:
    get:
      tags:
        - Albums
        - Library
      operationId: get-users-saved-albums
      summary: Get User's Saved Albums
      description: Get a list of the albums saved in the current Spotify user's 'Your Music' library.
      security:
        - oauth_2_0:
            - user-library-read
    put:
      tags:
        - Albums
        - Library
      operationId: save-albums-user
      summary: Save Albums for Current User
      description: Save one or more albums to the current user's 'Your Music' library.
      security:
        - oauth_2_0:
            - user-library-modify
    delete:
      tags:
        - Albums
        - Library
      operationId: remove-albums-user
      summary: Remove Users' Saved Albums
      description: Remove one or more albums from the current user's 'Your Music' library.
      security:
        - oauth_2_0:
            - user-library-modify

  /me/tracks:
    get:
      tags:
        - Tracks
        - Library
      operationId: get-users-saved-tracks
      summary: |
        Get User's Saved Tracks
      description: |
        Get a list of the songs saved in the current Spotify user's 'Your Music' library.
      security:
        - oauth_2_0:
            - user-library-read
    put:
      tags:
        - Tracks
        - Library
      operationId: save-tracks-user
      summary: |
        Save Tracks for Current User
      description: |
        Save one or more tracks to the current user's 'Your Music' library.
  /me/top/{type}:
    get:
      tags:
        - Users
        - Tracks
        - Library
      operationId: get-users-top-artists-and-tracks
      summary: |
        Get User's Top Items
      description: |
        Get the current user's top artists or tracks based on calculated affinity.
      security:
        - oauth_2_0:
            - user-top-read
  /me/player:
    get:
      tags:
        - Player
      operationId: get-information-about-the-users-current-playback
      summary: |
        Get Playback State
      description: |
        Get information about the user’s current playback state, including track or episode, progress, and active device.
      security:
        - oauth_2_0:
            - user-read-playback-state
    put:
      tags:
        - Player
      operationId: transfer-a-users-playback
      summary: |
        Transfer Playback
      description: |
        Transfer playback to a new device and determine if it should start playing.
      security:
        - oauth_2_0:
            - user-modify-playback-state
  /me/player/devices:
    get:
      tags:
        - Player
      operationId: get-a-users-available-devices
      summary: |
        Get Available Devices
      description: |
        Get information about a user’s available devices.

      security:
        - oauth_2_0:
            - user-read-playback-state
  /me/player/currently-playing:
    get:
      tags:
        - Player
      operationId: get-the-users-currently-playing-track
      summary: |
        Get Currently Playing Track
      description: |
        Get the object currently being played on the user's Spotify account.
      security:
        - oauth_2_0:
            - user-read-currently-playing

  /me/player/play:
    put:
      tags:
        - Player
      operationId: start-a-users-playback
      summary: |
        Start/Resume Playback
      description: |
        Start a new context or resume current playback on the user's active device.
      security:
        - oauth_2_0:
            - user-modify-playback-state
  /me/player/pause:
    put:
      tags:
        - Player
      operationId: pause-a-users-playback
      summary: |
        Pause Playback
      description: |
        Pause playback on the user's account.
      security:
        - oauth_2_0:
            - user-modify-playback-state
  /me/player/next:
    post:
      tags:
        - Player
      operationId: skip-users-playback-to-next-track
      summary: |
        Skip To Next
      description: |
        Skips to next track in the user’s queue.
      security:
        - oauth_2_0:
            - user-modify-playback-state
  /me/player/previous:
    post:
      tags:
        - Player
      operationId: skip-users-playback-to-previous-track
      summary: |
        Skip To Previous
      description: |
        Skips to previous track in the user’s queue.
      security:
        - oauth_2_0:
            - user-modify-playback-state
  /me/player/seek:
    put:
      tags:
        - Player
      operationId: seek-to-position-in-currently-playing-track
      summary: |
        Seek To Position
      description: |
        Seeks to the given position in the user’s currently playing track.
      security:
        - oauth_2_0:
            - user-modify-playback-state
  /me/player/repeat:
    put:
      tags:
        - Player
      operationId: set-repeat-mode-on-users-playback
      summary: |
        Set Repeat Mode
      description: |
        Set the repeat mode for the user's playback. Options are repeat-track,
        repeat-context, and off.
      security:
        - oauth_2_0:
            - user-modify-playback-state
  /me/player/volume:
    put:
      tags:
        - Player
      operationId: set-volume-for-users-playback
      summary: |
        Set Playback Volume
      description: |
        Set the volume for the user’s current playback device.
      security:
        - oauth_2_0:
            - user-modify-playback-state
  /me/player/shuffle:
    put:
      tags:
        - Player
      operationId: toggle-shuffle-for-users-playback
      summary: |
        Toggle Playback Shuffle
      description: |
        Toggle shuffle on or off for user’s playback.
      security:
        - oauth_2_0:
            - user-modify-playback-state
  /me/player/recently-played:
    get:
      tags:
        - Player
      operationId: get-recently-played
      summary: |
        Get Recently Played Tracks
      description: |
        Get tracks from the current user's recently played tracks.
        _**Note**: Currently doesn't support podcast episodes._
      security:
        - oauth_2_0:
            - user-read-recently-played
  /me/player/queue:
    get:
      tags:
        - Player
      operationId: get-queue
      summary: |
        Get the User's Queue
      description: |
        Get the list of objects that make up the user's queue.

      security:
        - oauth_2_0:
            - user-read-playback-state
    post:
      tags:
        - Player
      operationId: add-to-queue
      summary: |
        Add Item to Playback Queue
      description: |
        Add an item to the end of the user's current playback queue.
      security:
        - oauth_2_0:
            - user-modify-playback-state

components: